on:
  pull_request:
    branches: [master, v1]
  push:
    branches: [master, v1]
jobs:
    goreadme:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Update readme according to Go doc
          uses: posener/goreadme@v1.2.6
          with:
            recursive: 'true'
            badge-travisci: 'true'
            badge-codecov: 'true'
            github-token: '${{ secrets.GITHUB_TOKEN }}'
